### ISSUE TITLE
IP Geolocation granularity impacts

### ISSUE THREAD

**Issue by smhendrickson** [spanicker/ip-blindness#20]
IETF RFC 8805 allows for country, ‘region’ (state in US), and city level mappings to be advertised. While the IP Protection proposal will not retain all state/city level granularity, we would like to retain enough to keep inferred geographic content relevant to users, and GeoIP based performance optimizations functioning.

To achieve this, Chrome is considering mapping many unique cities/regions to groups of combined cities/regions. We call these Geos. We are considering using a threshold of 1 million estimated human population for each created geo. This geo will then be shared in the public IP Geolocation feed. 

Which use cases of yours would 1 million people sufficiently cover and which use cases would not be sufficiently covered?

**Comment by miketaylr** [comment]
Closing and locking in favor of https://github.com/GoogleChrome/ip-protection/issues/3
