### ISSUE TITLE
Loss of IP Metadata

### ISSUE THREAD

**Issue by jbradl11** [spanicker/ip-blindness#22]
IP addresses serve a variety of use cases beyond anti-fraud. IP can be used for analytics, measurement, regional preferences, tracking paid subscribers, and many more. As Chrome seeks to mask IP addresses, we are working to ensure that valid use cases are preserved while also improving privacy on the web. 

How does blocking IP challenge your different use cases? What other ways could actors achieve these use cases without IP addresses used for fingerprinting? What potential replacement signals could we extract from an IP address and pass as a new, standalone (and possibly attested?) signal?

**Comment by miketaylr** [comment]
Closing and locking in favor of https://github.com/GoogleChrome/ip-protection/issues/1
